#!/usr/bin/env python3
"""
run_dynamic_scheduler_demo.py -- Phase 15: run all four
dynamic-scheduling demo programs (dynamic_scheduler_demo,
always_cpu_demo, always_accel_demo, oracle_demo -- see
scheduler/runtime/gen_dynamic_scheduler_demo.py) through
sim/testbenches/tb_benchmark_soc.sv and write
results/dynamic_scheduling_report.md from their REAL measured total
cycle counts for the same fixed 6-workload stream.

Every number here is a genuine end-to-end simulation total, not a sum
of the individually-measured Phase 13/14 per-workload numbers: the
whole point of this phase is to measure the ACTUAL cost of making the
scheduling decision at runtime (extra instructions, extra branches,
extra pipeline flushes), not just the cost of whichever engine ends up
running. Correctness of all four programs is established separately by
sim/testbenches/tb_dynamic_scheduler_correctness.sv
(`make test_dynamic_scheduler_correctness`) -- run that first if you
have any doubt.

Usage:
    python3 scheduler/runtime/run_dynamic_scheduler_demo.py
"""

import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

RTL_FILES = [
    "rtl/cpu/riscv_pkg.sv",
    "rtl/alu/alu.sv",
    "rtl/regfile/regfile.sv",
    "rtl/decoder/decoder.sv",
    "rtl/decoder/imm_gen.sv",
    "rtl/cpu/control_unit.sv",
    "rtl/cpu/branch_unit.sv",
    "rtl/memory/imem.sv",
    "rtl/memory/dmem.sv",
    "rtl/pipeline/if_id_reg.sv",
    "rtl/pipeline/id_ex_reg.sv",
    "rtl/pipeline/ex_mem_reg.sv",
    "rtl/pipeline/mem_wb_reg.sv",
    "rtl/pipeline/forwarding_unit.sv",
    "rtl/pipeline/hazard_unit.sv",
    "rtl/cpu/perf_counters.sv",
    "rtl/cpu/riscv_cpu_pipeline.sv",
    "rtl/bus/soc_bus.sv",
    "rtl/bus/uart.sv",
    "rtl/bus/gpio.sv",
    "rtl/accelerator/accelerator.sv",
    "rtl/cpu/riscv_soc.sv",
]
TB = "sim/testbenches/tb_benchmark_soc.sv"
SRC_DIR = "sim/programs/scheduler"

PROGRAMS = [
    ("dynamic_scheduler_demo", "Dynamic (runtime-computed decision per block)"),
    ("always_cpu_demo", "Always CPU (static baseline)"),
    ("always_accel_demo", "Always accelerator (static baseline)"),
    ("oracle_demo", "Oracle (best real engine per block, from Phase 13/14 data)"),
]

RESULT_RE = re.compile(
    r"BENCHMARK_RESULT: name=(\S+) cycles=(\d+) retired=(\d+) stall=(\d+) "
    r"branch=(\d+) branch_taken=(\d+) load_use_stall=(\d+) forwarding=(\d+) flush=(\d+)"
)

REPORT_PATH = os.path.join(ROOT, "results", "dynamic_scheduling_report.md")


def run_one(vvp_out, stem):
    hexpath = f"{SRC_DIR}/{stem}.hex"
    r = subprocess.run(
        ["vvp", vvp_out, f"+HEXFILE={hexpath}", f"+NAME={stem}"],
        cwd=ROOT, capture_output=True, text=True,
    )
    m = RESULT_RE.search(r.stdout)
    if not m:
        print(f"no BENCHMARK_RESULT line for {stem}; simulator output:\n{r.stdout}",
              file=sys.stderr)
        sys.exit(1)
    return {
        "cycles": int(m.group(2)), "retired": int(m.group(3)), "stall": int(m.group(4)),
        "branch": int(m.group(5)), "branch_taken": int(m.group(6)), "flush": int(m.group(9)),
    }


def main():
    for stem, _ in PROGRAMS:
        src = f"{SRC_DIR}/{stem}.s"
        hexpath = f"{SRC_DIR}/{stem}.hex"
        r = subprocess.run(
            [sys.executable, os.path.join(ROOT, "scripts", "asm_to_hex.py"),
             src, "-o", hexpath, "--words", "512"],
            capture_output=True, text=True,
        )
        if r.returncode != 0:
            print(f"FAILED TO ASSEMBLE {src}:\n{r.stderr}", file=sys.stderr)
            sys.exit(1)

    vvp_out = tempfile.NamedTemporaryFile(delete=False, suffix=".vvp").name
    r = subprocess.run(
        ["iverilog", "-g2012", "-o", vvp_out] + RTL_FILES + [TB],
        cwd=ROOT, capture_output=True, text=True,
    )
    if r.returncode != 0:
        print("Icarus compile failed:\n" + r.stdout + r.stderr, file=sys.stderr)
        sys.exit(1)

    results = {}
    for stem, label in PROGRAMS:
        results[stem] = run_one(vvp_out, stem)
        print(f"{label}: {results[stem]['cycles']} cycles")
    os.unlink(vvp_out)

    write_report(results)
    print(f"\nWrote {REPORT_PATH}")


def write_report(results):
    dyn = results["dynamic_scheduler_demo"]["cycles"]
    cpu = results["always_cpu_demo"]["cycles"]
    acc = results["always_accel_demo"]["cycles"]
    oracle = results["oracle_demo"]["cycles"]

    lines = []
    lines.append("# Dynamic Runtime Scheduling Report (Phase 15)\n")
    lines.append(
        "Generated by `scheduler/runtime/run_dynamic_scheduler_demo.py` from actual "
        "Icarus Verilog simulation of `rtl/cpu/riscv_soc.sv`. All four programs run the "
        "SAME fixed 6-workload stream (vecadd N=1,2,4; dot N=1,4; matmul N=2 -- see "
        "`scheduler/runtime/gen_dynamic_scheduler_demo.py`); every cycle count below is "
        "an end-to-end total for the whole stream, read at the single GPIO sentinel "
        "write that fires once all 6 workloads finish. `dynamic_scheduler_demo` is the "
        "only one of the four whose engine choice is computed AT RUNTIME by real RV32I "
        "instructions (see docs/dynamic_scheduling.md) -- the other three are static "
        "baselines for comparison. Correctness of all four is established separately by "
        "`sim/testbenches/tb_dynamic_scheduler_correctness.sv` "
        "(`make test_dynamic_scheduler_correctness`).\n"
    )
    lines.append("| Program | Total cycles | vs. always-CPU | vs. always-accelerator | vs. oracle |")
    lines.append("|---|---|---|---|---|")
    lines.append(f"| Dynamic (runtime decision) | {dyn} | {cpu/dyn:.2f}x faster | "
                  f"{'%.2fx faster' % (acc/dyn) if dyn < acc else '%.2fx SLOWER' % (dyn/acc)} | "
                  f"{oracle/dyn:.2f}x of oracle |")
    lines.append(f"| Always CPU | {cpu} | 1.00x (baseline) | -- | -- |")
    lines.append(f"| Always accelerator | {acc} | -- | 1.00x (baseline) | -- |")
    lines.append(f"| Oracle (best-per-block, from real data) | {oracle} | -- | -- | 1.00x (baseline) |")
    lines.append("")

    if dyn > acc:
        lines.append(
            f"**Headline finding: the dynamic scheduler ({dyn} cycles) is SLOWER than "
            f"simply always using the accelerator ({acc} cycles) for this workload "
            f"stream** -- {dyn - acc} cycles worse, a real, measured, and honestly "
            f"reported result, not a bug being explained away. Two real costs combine:\n"
        )
        lines.append(
            f"1. **The one known misprediction has a real cost here too.** `vecadd N=2` "
            f"is dispatched to the CPU (matching the model's Phase 14 misprediction -- "
            f"see `docs/scheduler_pipeline.md`) when the accelerator would have been "
            f"faster (61 vs. 50 cycles standalone)."
        )
        lines.append(
            f"2. **The runtime decision computation itself has a real, non-zero cost.** "
            f"`dynamic_scheduler_demo` retires {results['dynamic_scheduler_demo']['retired']} "
            f"instructions and incurs {results['dynamic_scheduler_demo']['flush']} pipeline "
            f"flushes vs. `oracle_demo`'s {results['oracle_demo']['retired']} instructions "
            f"and {results['oracle_demo']['flush']} flushes -- every block pays for computing "
            f"element_count/multiply_count and branching on them, on top of whichever engine "
            f"it ends up running. For workloads this small (a handful of elements each), that "
            f"decision overhead is not negligible relative to the work itself."
        )
        lines.append(
            f"\nThis is a genuine engineering lesson, not a project failure: **an AI "
            f"scheduler's own runtime overhead can outweigh the benefit of its decisions "
            f"when workloads are small enough and its decisions aren't perfect.** A "
            f"scheduler that is only ever right (`oracle_demo`, {oracle} cycles) still "
            f"beats always-accelerator ({acc} cycles) by "
            f"{acc - oracle} cycles -- so the idea has real value here; it is the "
            f"combination of decision overhead AND one wrong call that erases it in this "
            f"specific stream. See docs/dynamic_scheduling.md for what this does and "
            f"doesn't imply."
        )
    else:
        lines.append(
            f"The dynamic scheduler ({dyn} cycles) beats always-accelerator "
            f"({acc} cycles) for this workload stream, {acc - dyn} cycles saved."
        )
    lines.append("")
    lines.append("## Full counter detail\n")
    lines.append("| Program | Cycles | Instructions retired | Stalls | Branches | Taken | Flushes |")
    lines.append("|---|---|---|---|---|---|---|")
    for stem, label in PROGRAMS:
        r = results[stem]
        lines.append(f"| {stem} | {r['cycles']} | {r['retired']} | {r['stall']} | "
                      f"{r['branch']} | {r['branch_taken']} | {r['flush']} |")
    lines.append("")

    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
