# cpu_matmul_mul_n8.s -- generated by scheduler/benchmarks/gen_mul_programs.py: the
# Phase 13 template below with `jal x1, mul32` replaced by the hardware
# RV32M `mul x10, x11, x12` (needs a core built with ENABLE_MUL=1).
# cpu_matmul_n8.s -- Phase 13 scheduler dataset: CPU-only 8x8
# matrix multiply. Generated from
# sim/programs/benchmarks/cpu_matmul_bench.s's structure (Phase 11);
# the loop bound N and the "i*N"/"k*N" address shift (3 =
# log2(8)) both differ -- see this generator script's own header
# comment for why N is restricted to powers of two here (keeps the
# multiply-by-N in address computation a single `slli`, matching
# Phase 11's real, already-verified hardware timing, rather than
# introducing a software multiply that would change what's measured).

    li   x23, 0x1000
    li   x2, 0x2000
    li   x3, 0x3000
    li   x9, 8
    li   x29, 0x20000000
    li   x30, 0xDEADBEEF

    li   x13, 0
setup_i:
    li   x14, 0
setup_j:
    add  x15, x13, x14
    slli x16, x13, 3
    add  x16, x16, x14
    slli x16, x16, 2

    addi x17, x15, 1
    add  x18, x23, x16
    sw   x17, 0(x18)

    addi x17, x15, 2
    add  x18, x2, x16
    sw   x17, 0(x18)

    addi x14, x14, 1
    bne  x14, x9, setup_j
    addi x13, x13, 1
    bne  x13, x9, setup_i

    li   x13, 0
mm_i:
    li   x14, 0
mm_j:
    li   x19, 0
    li   x21, 0
mm_k:
    slli x16, x13, 3
    add  x16, x16, x21
    slli x16, x16, 2
    add  x18, x23, x16
    lw   x11, 0(x18)

    slli x16, x21, 3
    add  x16, x16, x14
    slli x16, x16, 2
    add  x18, x2, x16
    lw   x12, 0(x18)

    mul  x10, x11, x12
    add  x19, x19, x10

    addi x21, x21, 1
    bne  x21, x9, mm_k

    slli x16, x13, 3
    add  x16, x16, x14
    slli x16, x16, 2
    add  x18, x3, x16
    sw   x19, 0(x18)

    addi x14, x14, 1
    bne  x14, x9, mm_j
    addi x13, x13, 1
    bne  x13, x9, mm_i

    sw   x30, 0(x29)
    j    done


done:
    j done
