# cpu_dot_mul_n16.s -- generated by scheduler/benchmarks/gen_mul_programs.py: the
# Phase 13 template below with `jal x1, mul32` replaced by the hardware
# RV32M `mul x10, x11, x12` (needs a core built with ENABLE_MUL=1).
# cpu_dot_n16.s -- Phase 13 scheduler dataset: CPU-only dot product,
# N=16. Generated from sim/programs/benchmarks/cpu_dot_bench.s's
# structure (Phase 11); only the loop bound N differs. Uses the mul32
# software multiply routine (see mul32_test.s), and keeps &A[0] in
# x23, NOT x1, for the same real reason documented in
# cpu_dot_bench.s's header comment (x1 is jal's return-address
# register; a real bug from this exact mistake is in CHANGELOG.md's
# Phase 11 entry).

    li   x23, 0x1000
    li   x2,  0x2000
    li   x9,  16
    li   x29, 0x20000000
    li   x30, 0xDEADBEEF
    li   x20, 0

    li   x4, 0
setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x23, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, setup_loop

    li   x4, 0
compute_loop:
    slli x6, x4, 2
    add  x7, x23, x6
    lw   x11, 0(x7)
    add  x7, x2, x6
    lw   x12, 0(x7)
    mul  x10, x11, x12
    add  x20, x20, x10
    addi x4, x4, 1
    bne  x4, x9, compute_loop

    sw   x30, 0(x29)
    j    done


done:
    j done
