# cpu_vecadd_n1.s -- Phase 13 scheduler dataset: CPU-only vector add,
# N=1. Generated by scheduler/benchmarks/gen_scheduler_programs.py
# from the exact structure of sim/programs/benchmarks/cpu_vecadd_bench.s
# (Phase 11) -- see that file and docs/scheduler.md for the full
# rationale; only the loop bound N differs.

    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3000
    li   x9, 1
    li   x29, 0x20000000
    li   x30, 0xDEADBEEF

    li   x4, 0
setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, setup_loop

    li   x4, 0
compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, compute_loop

    sw   x30, 0(x29)
done:
    j    done
