# mixed_dynamic_lean_demo.s -- Phase 16's 12-workload stream, v2 model, lean runtime decision
# (generated by scheduler/runtime/gen_dynamic_lean_demo.py -- see its
# docstring for what is folded, what is still decided at runtime, and why).

    li   x29, 0x20000000
    li   x30, 0xDEADBEEF
    li   x28, 1

# -- block k0: vecadd N=1 (runtime compare: cpu iff N <= threshold) --
    li   x9, 1
    bge  x28, x9, k0_cpu
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x4, 0
k0a_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k0a_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

k0a_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k0a_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3000
    lw   x25, 0(x24)
    sw   x25, 0(x26)
k0_done:

# -- block k1: vecadd N=2 (runtime compare: cpu iff N <= threshold) --
    li   x9, 2
    bge  x28, x9, k1_cpu
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x4, 0
k1a_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k1a_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

k1a_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k1a_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3100
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
k1_done:

# -- block k2: dot N=4 (folded: accelerator for every legal N) --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 4
    li   x4, 0
k2_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k2_setup_loop

    sw   x9, 8(x1)
    accel.dot

k2_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k2_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x3200
    sw   x25, 0(x26)

# -- block k3: matmul N=2 (folded: accelerator for every legal N) --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 2

    li   x13, 0
k3_setup_i:
    li   x14, 0
k3_setup_j:
    add  x15, x13, x14
    slli x16, x13, 1
    add  x16, x16, x14
    slli x16, x16, 2

    addi x17, x15, 1
    add  x18, x2, x16
    sw   x17, 0(x18)

    addi x17, x15, 2
    add  x18, x3, x16
    sw   x17, 0(x18)

    addi x14, x14, 1
    bne  x14, x9, k3_setup_j
    addi x13, x13, 1
    bne  x13, x9, k3_setup_i

    sw   x9, 8(x1)
    accel.matmul

k3_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k3_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3300
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)

# -- block k4: vecadd N=4 (runtime compare: cpu iff N <= threshold) --
    li   x9, 4
    bge  x28, x9, k4_cpu
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x4, 0
k4a_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k4a_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

k4a_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k4a_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3400
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
k4_done:

# -- block k5: dot N=8 (folded: accelerator for every legal N) --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 8
    li   x4, 0
k5_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k5_setup_loop

    sw   x9, 8(x1)
    accel.dot

k5_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k5_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x3500
    sw   x25, 0(x26)

# -- block k6: vecadd N=8 (runtime compare: cpu iff N <= threshold) --
    li   x9, 8
    bge  x28, x9, k6_cpu
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x4, 0
k6a_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k6a_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

k6a_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k6a_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3600
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)
k6_done:

# -- block k7: matmul N=4 (folded: accelerator for every legal N) --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 4

    li   x13, 0
k7_setup_i:
    li   x14, 0
k7_setup_j:
    add  x15, x13, x14
    slli x16, x13, 2
    add  x16, x16, x14
    slli x16, x16, 2

    addi x17, x15, 1
    add  x18, x2, x16
    sw   x17, 0(x18)

    addi x17, x15, 2
    add  x18, x3, x16
    sw   x17, 0(x18)

    addi x14, x14, 1
    bne  x14, x9, k7_setup_j
    addi x13, x13, 1
    bne  x13, x9, k7_setup_i

    sw   x9, 8(x1)
    accel.matmul

k7_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k7_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3700
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)
    lw   x25, 32(x24)
    sw   x25, 32(x26)
    lw   x25, 36(x24)
    sw   x25, 36(x26)
    lw   x25, 40(x24)
    sw   x25, 40(x26)
    lw   x25, 44(x24)
    sw   x25, 44(x26)
    lw   x25, 48(x24)
    sw   x25, 48(x26)
    lw   x25, 52(x24)
    sw   x25, 52(x26)
    lw   x25, 56(x24)
    sw   x25, 56(x26)
    lw   x25, 60(x24)
    sw   x25, 60(x26)

# -- block k8: dot N=16 (folded: accelerator for every legal N) --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 16
    li   x4, 0
k8_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k8_setup_loop

    sw   x9, 8(x1)
    accel.dot

k8_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k8_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x3800
    sw   x25, 0(x26)

# -- block k9: vecadd N=16 (runtime compare: cpu iff N <= threshold) --
    li   x9, 16
    bge  x28, x9, k9_cpu
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x4, 0
k9a_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k9a_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

k9a_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k9a_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3900
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)
    lw   x25, 32(x24)
    sw   x25, 32(x26)
    lw   x25, 36(x24)
    sw   x25, 36(x26)
    lw   x25, 40(x24)
    sw   x25, 40(x26)
    lw   x25, 44(x24)
    sw   x25, 44(x26)
    lw   x25, 48(x24)
    sw   x25, 48(x26)
    lw   x25, 52(x24)
    sw   x25, 52(x26)
    lw   x25, 56(x24)
    sw   x25, 56(x26)
    lw   x25, 60(x24)
    sw   x25, 60(x26)
k9_done:

# -- block k10: dot N=32 (folded: accelerator for every legal N) --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 32
    li   x4, 0
k10_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k10_setup_loop

    sw   x9, 8(x1)
    accel.dot

k10_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k10_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x3a00
    sw   x25, 0(x26)

# -- block k11: vecadd N=32 (runtime compare: cpu iff N <= threshold) --
    li   x9, 32
    bge  x28, x9, k11_cpu
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x4, 0
k11a_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k11a_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

k11a_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, k11a_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3b00
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)
    lw   x25, 32(x24)
    sw   x25, 32(x26)
    lw   x25, 36(x24)
    sw   x25, 36(x26)
    lw   x25, 40(x24)
    sw   x25, 40(x26)
    lw   x25, 44(x24)
    sw   x25, 44(x26)
    lw   x25, 48(x24)
    sw   x25, 48(x26)
    lw   x25, 52(x24)
    sw   x25, 52(x26)
    lw   x25, 56(x24)
    sw   x25, 56(x26)
    lw   x25, 60(x24)
    sw   x25, 60(x26)
    lw   x25, 64(x24)
    sw   x25, 64(x26)
    lw   x25, 68(x24)
    sw   x25, 68(x26)
    lw   x25, 72(x24)
    sw   x25, 72(x26)
    lw   x25, 76(x24)
    sw   x25, 76(x26)
    lw   x25, 80(x24)
    sw   x25, 80(x26)
    lw   x25, 84(x24)
    sw   x25, 84(x26)
    lw   x25, 88(x24)
    sw   x25, 88(x26)
    lw   x25, 92(x24)
    sw   x25, 92(x26)
    lw   x25, 96(x24)
    sw   x25, 96(x26)
    lw   x25, 100(x24)
    sw   x25, 100(x26)
    lw   x25, 104(x24)
    sw   x25, 104(x26)
    lw   x25, 108(x24)
    sw   x25, 108(x26)
    lw   x25, 112(x24)
    sw   x25, 112(x26)
    lw   x25, 116(x24)
    sw   x25, 116(x26)
    lw   x25, 120(x24)
    sw   x25, 120(x26)
    lw   x25, 124(x24)
    sw   x25, 124(x26)
k11_done:

    sw   x30, 0(x29)
done:
    j    done

# -- cold path for block k0 --
k0_cpu:
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3000

    li   x4, 0
k0c_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k0c_setup_loop

    li   x4, 0
k0c_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k0c_compute_loop
    j    k0_done

# -- cold path for block k1 --
k1_cpu:
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3100

    li   x4, 0
k1c_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k1c_setup_loop

    li   x4, 0
k1c_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k1c_compute_loop
    j    k1_done

# -- cold path for block k4 --
k4_cpu:
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3400

    li   x4, 0
k4c_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k4c_setup_loop

    li   x4, 0
k4c_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k4c_compute_loop
    j    k4_done

# -- cold path for block k6 --
k6_cpu:
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3600

    li   x4, 0
k6c_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k6c_setup_loop

    li   x4, 0
k6c_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k6c_compute_loop
    j    k6_done

# -- cold path for block k9 --
k9_cpu:
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3900

    li   x4, 0
k9c_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k9c_setup_loop

    li   x4, 0
k9c_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k9c_compute_loop
    j    k9_done

# -- cold path for block k11 --
k11_cpu:
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3b00

    li   x4, 0
k11c_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k11c_setup_loop

    li   x4, 0
k11c_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, k11c_compute_loop
    j    k11_done

mul32:
    li   x10, 0
    mv   x5, x11
    mv   x6, x12
mul32_loop:
    beq  x6, x0, mul32_done
    andi x7, x6, 1
    beq  x7, x0, mul32_skip
    add  x10, x10, x5
mul32_skip:
    slli x5, x5, 1
    srli x6, x6, 1
    j    mul32_loop
mul32_done:
    ret
