# phase16, rv32i core, always_accel
# generated by scheduler/coschedule/codegen.py -- see docs/coschedule.md

    li   x29, 0x20000000
    li   x30, 0xDEADBEEF

# -- task 0: vecadd N=1 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 1
    li   x4, 0
t0_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t0_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

t0_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t0_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3000
    lw   x25, 0(x24)
    sw   x25, 0(x26)

# -- task 1: vecadd N=2 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 2
    li   x4, 0
t1_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t1_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

t1_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t1_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3004
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)

# -- task 2: dot N=4 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 4
    li   x4, 0
t2_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t2_setup_loop

    sw   x9, 8(x1)
    accel.dot

t2_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t2_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x300c
    sw   x25, 0(x26)

# -- task 3: matmul N=2 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 2

    li   x13, 0
t3_setup_i:
    li   x14, 0
t3_setup_j:
    add  x15, x13, x14
    slli x16, x13, 1
    add  x16, x16, x14
    slli x16, x16, 2

    addi x17, x15, 1
    add  x18, x2, x16
    sw   x17, 0(x18)

    addi x17, x15, 2
    add  x18, x3, x16
    sw   x17, 0(x18)

    addi x14, x14, 1
    bne  x14, x9, t3_setup_j
    addi x13, x13, 1
    bne  x13, x9, t3_setup_i

    sw   x9, 8(x1)
    accel.matmul

t3_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t3_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3010
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)

# -- task 4: vecadd N=4 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 4
    li   x4, 0
t4_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t4_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

t4_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t4_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3020
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)

# -- task 5: dot N=8 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 8
    li   x4, 0
t5_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t5_setup_loop

    sw   x9, 8(x1)
    accel.dot

t5_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t5_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x3030
    sw   x25, 0(x26)

# -- task 6: vecadd N=8 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 8
    li   x4, 0
t6_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t6_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

t6_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t6_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3034
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)

# -- task 7: matmul N=4 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 4

    li   x13, 0
t7_setup_i:
    li   x14, 0
t7_setup_j:
    add  x15, x13, x14
    slli x16, x13, 2
    add  x16, x16, x14
    slli x16, x16, 2

    addi x17, x15, 1
    add  x18, x2, x16
    sw   x17, 0(x18)

    addi x17, x15, 2
    add  x18, x3, x16
    sw   x17, 0(x18)

    addi x14, x14, 1
    bne  x14, x9, t7_setup_j
    addi x13, x13, 1
    bne  x13, x9, t7_setup_i

    sw   x9, 8(x1)
    accel.matmul

t7_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t7_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3054
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)
    lw   x25, 32(x24)
    sw   x25, 32(x26)
    lw   x25, 36(x24)
    sw   x25, 36(x26)
    lw   x25, 40(x24)
    sw   x25, 40(x26)
    lw   x25, 44(x24)
    sw   x25, 44(x26)
    lw   x25, 48(x24)
    sw   x25, 48(x26)
    lw   x25, 52(x24)
    sw   x25, 52(x26)
    lw   x25, 56(x24)
    sw   x25, 56(x26)
    lw   x25, 60(x24)
    sw   x25, 60(x26)

# -- task 8: dot N=16 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 16
    li   x4, 0
t8_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t8_setup_loop

    sw   x9, 8(x1)
    accel.dot

t8_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t8_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x3094
    sw   x25, 0(x26)

# -- task 9: vecadd N=16 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 16
    li   x4, 0
t9_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t9_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

t9_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t9_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3098
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)
    lw   x25, 32(x24)
    sw   x25, 32(x26)
    lw   x25, 36(x24)
    sw   x25, 36(x26)
    lw   x25, 40(x24)
    sw   x25, 40(x26)
    lw   x25, 44(x24)
    sw   x25, 44(x26)
    lw   x25, 48(x24)
    sw   x25, 48(x26)
    lw   x25, 52(x24)
    sw   x25, 52(x26)
    lw   x25, 56(x24)
    sw   x25, 56(x26)
    lw   x25, 60(x24)
    sw   x25, 60(x26)

# -- task 10: dot N=32 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 32
    li   x4, 0
t10_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t10_setup_loop

    sw   x9, 8(x1)
    accel.dot

t10_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t10_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x30d8
    sw   x25, 0(x26)

# -- task 11: vecadd N=32 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 32
    li   x4, 0
t11_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t11_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

t11_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t11_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x30dc
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)
    lw   x25, 16(x24)
    sw   x25, 16(x26)
    lw   x25, 20(x24)
    sw   x25, 20(x26)
    lw   x25, 24(x24)
    sw   x25, 24(x26)
    lw   x25, 28(x24)
    sw   x25, 28(x26)
    lw   x25, 32(x24)
    sw   x25, 32(x26)
    lw   x25, 36(x24)
    sw   x25, 36(x26)
    lw   x25, 40(x24)
    sw   x25, 40(x26)
    lw   x25, 44(x24)
    sw   x25, 44(x26)
    lw   x25, 48(x24)
    sw   x25, 48(x26)
    lw   x25, 52(x24)
    sw   x25, 52(x26)
    lw   x25, 56(x24)
    sw   x25, 56(x26)
    lw   x25, 60(x24)
    sw   x25, 60(x26)
    lw   x25, 64(x24)
    sw   x25, 64(x26)
    lw   x25, 68(x24)
    sw   x25, 68(x26)
    lw   x25, 72(x24)
    sw   x25, 72(x26)
    lw   x25, 76(x24)
    sw   x25, 76(x26)
    lw   x25, 80(x24)
    sw   x25, 80(x26)
    lw   x25, 84(x24)
    sw   x25, 84(x26)
    lw   x25, 88(x24)
    sw   x25, 88(x26)
    lw   x25, 92(x24)
    sw   x25, 92(x26)
    lw   x25, 96(x24)
    sw   x25, 96(x26)
    lw   x25, 100(x24)
    sw   x25, 100(x26)
    lw   x25, 104(x24)
    sw   x25, 104(x26)
    lw   x25, 108(x24)
    sw   x25, 108(x26)
    lw   x25, 112(x24)
    sw   x25, 112(x26)
    lw   x25, 116(x24)
    sw   x25, 116(x26)
    lw   x25, 120(x24)
    sw   x25, 120(x26)
    lw   x25, 124(x24)
    sw   x25, 124(x26)

    sw   x30, 0(x29)
done:
    j    done

mul32:
    li   x10, 0
    mv   x5, x11
    mv   x6, x12
mul32_loop:
    beq  x6, x0, mul32_done
    andi x7, x6, 1
    beq  x7, x0, mul32_skip
    add  x10, x10, x5
mul32_skip:
    slli x5, x5, 1
    srli x6, x6, 1
    j    mul32_loop
mul32_done:
    ret
