# phase15, rv32i core, cosched
# generated by scheduler/coschedule/codegen.py -- see docs/coschedule.md

    li   x29, 0x20000000
    li   x30, 0xDEADBEEF

# -- task 2: vecadd N=4 on accelerator, window hosts tasks [1] --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 4
    li   x4, 0
t2_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t2_setup_loop

    sw   x9, 8(x1)
    accel.vecadd

# ---- window: task 1: vecadd N=2 on CPU, while task 2 computes ----
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3004
    li   x9, 2

    li   x4, 0
t1_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t1_setup_loop

    li   x4, 0
t1_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t1_compute_loop
    li   x1, 0x30000000   # CPU tasks reused x1; restore MMIO base
t2_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t2_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x300c
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)

# -- task 3: dot N=1 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 1
    li   x4, 0
t3_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t3_setup_loop

    sw   x9, 8(x1)
    accel.dot

t3_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t3_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x301c
    sw   x25, 0(x26)

# -- task 4: dot N=4 on accelerator --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 4
    li   x4, 0
t4_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x2, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x3, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t4_setup_loop

    sw   x9, 8(x1)
    accel.dot

t4_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t4_wait_loop

    lw   x25, 12(x1)
    li   x26, 0x3020
    sw   x25, 0(x26)

# -- task 5: matmul N=2 on accelerator, window hosts tasks [0] --
    li   x1, 805306368
    li   x2, 0x1000
    li   x3, 0x2000
    add  x2, x1, x2
    add  x3, x1, x3

    li   x9, 2

    li   x13, 0
t5_setup_i:
    li   x14, 0
t5_setup_j:
    add  x15, x13, x14
    slli x16, x13, 1
    add  x16, x16, x14
    slli x16, x16, 2

    addi x17, x15, 1
    add  x18, x2, x16
    sw   x17, 0(x18)

    addi x17, x15, 2
    add  x18, x3, x16
    sw   x17, 0(x18)

    addi x14, x14, 1
    bne  x14, x9, t5_setup_j
    addi x13, x13, 1
    bne  x13, x9, t5_setup_i

    sw   x9, 8(x1)
    accel.matmul

# ---- window: task 0: vecadd N=1 on CPU, while task 5 computes ----
    li   x1, 0x1000
    li   x2, 0x2000
    li   x3, 0x3000
    li   x9, 1

    li   x4, 0
t0_setup_loop:
    addi x5, x4, 1
    slli x6, x4, 2
    add  x7, x1, x6
    sw   x5, 0(x7)
    addi x8, x4, 2
    add  x7, x2, x6
    sw   x8, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t0_setup_loop

    li   x4, 0
t0_compute_loop:
    slli x6, x4, 2
    add  x7, x1, x6
    lw   x5, 0(x7)
    add  x7, x2, x6
    lw   x8, 0(x7)
    add  x5, x5, x8
    add  x7, x3, x6
    sw   x5, 0(x7)
    addi x4, x4, 1
    bne  x4, x9, t0_compute_loop
    li   x1, 0x30000000   # CPU tasks reused x1; restore MMIO base
t5_wait_loop:
    accel.stat x6
    andi x7, x6, 1
    bne  x7, x0, t5_wait_loop

    li   x24, 0x3000
    add  x24, x1, x24
    li   x26, 0x3024
    lw   x25, 0(x24)
    sw   x25, 0(x26)
    lw   x25, 4(x24)
    sw   x25, 4(x26)
    lw   x25, 8(x24)
    sw   x25, 8(x26)
    lw   x25, 12(x24)
    sw   x25, 12(x26)

    sw   x30, 0(x29)
done:
    j    done

mul32:
    li   x10, 0
    mv   x5, x11
    mv   x6, x12
mul32_loop:
    beq  x6, x0, mul32_done
    andi x7, x6, 1
    beq  x7, x0, mul32_skip
    add  x10, x10, x5
mul32_skip:
    slli x5, x5, 1
    srli x6, x6, 1
    j    mul32_loop
mul32_done:
    ret
